default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  password: postgres

development:
  <<: *default
  database: gachat_development

test:
  <<: *default
  database: gachat_test

production:
  <<: *default
  database: gachat_production
